using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GenarateLevel : MonoBehaviour
{
    public GameObject[] Section;
    public int zPos = 50;
    public bool creatingSection = false;
    public int secNum;

    void Update()
    {
        if (creatingSection == false)
        {
            creatingSection = true;
            StartCoroutine(GenerateSection());
        }
    }

    IEnumerator GenerateSection()
    {
        secNum = Random.Range(0, 1);
        Instantiate(Section[secNum], new Vector3(0, 0, zPos), Quaternion.identity);
        zPos += 50;
        yield return new WaitForSeconds(2);
        creatingSection = false;
    }
}